"$schema" = 'https://starship.rs/config-schema.json'

format = """$all\
$kubernetes\
$time\
$line_break\
$character"""

[directory]
truncation_length = 0
before_repo_root_style = "cyan"
repo_root_style = "bold cyan"
fish_style_pwd_dir_length = 3

[git_branch]
format = '[$branch(:$remote_branch)]($style) '

[kubernetes]
disabled = false
format = '[☸$context(\($namespace\))]($style) '

[time]
disabled = false
format = '[$time]($style) '

[shlvl]
disabled = false
format = '[↕️$shlvl]($style) '

[nix_shell]
disabled = false
heuristic = true
format = '[❄️nix]($style) '
