"$schema" = 'https://starship.rs/config-schema.json'

format = """$all\
$kubernetes\
$time\
$line_break\
$character"""

[directory]
truncation_length = 0
before_repo_root_style = "cyan"
repo_root_style = "bold cyan"
fish_style_pwd_dir_length = 3

[git_branch]
format = '[$branch(:$remote_branch)]($style) '

[git_status]
format = '([$ahead_behind$all_status]($style) )'
conflicted = '󰘕 '
ahead = ' '
behind = ' '
diverged = ' '
untracked = ' '
stashed = ' '
modified = ' '
staged = ' '
renamed = ' '
deleted = ' '

[kubernetes]
disabled = false
format = '[$context(\($namespace\))]($style) '

[time]
disabled = false
format = '[$time]($style) '

[shlvl]
disabled = false
format = '[󰹹$shlvl]($style) '

[nix_shell]
disabled = true

[direnv]
disabled = false
format = '[$loaded]($style) '
allowed_msg = ''
not_allowed_msg = ''
denied_msg = ''
loaded_msg = '󱥾direnv'
unloaded_msg = ''

[golang]
format = '[$version]($style) '

[rust]
format = '[$version]($style) '

[package]
disabled = true

[terraform]
disabled = true

[nodejs]
format = '[($version)]($style) '

[cmd_duration]
format = '[󰔛$duration]($style) '
