# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d7f9e473-c9f3-49e5-a7a3-0dcbd8e096ca";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/f682b3a2-7821-41aa-a611-b5ebd796b3dc";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d7f9e473-c9f3-49e5-a7a3-0dcbd8e096ca";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/d7f9e473-c9f3-49e5-a7a3-0dcbd8e096ca";
    fsType = "btrfs";
    options = [ "subvol=log" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d7f9e473-c9f3-49e5-a7a3-0dcbd8e096ca";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/efi" = {
    device = "systemd-1";
    fsType = "autofs";
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/d7f9e473-c9f3-49e5-a7a3-0dcbd8e096ca";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  swapDevices = [{ device = "/swap/swapfile"; }];

  boot.resumeDevice = "/dev/mapper/cryptroot";
  boot.kernelParams = [ "resume_offset=5514496" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwp0s20f0u4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
