name: Check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix fmt -- --check .
    - run: nix run nixpkgs#statix -- check --ignore hardware-configuration.nix
    - uses: DeterminateSystems/flake-checker-action@main
    - run: nix flake check --all-systems
